### ISSUE TITLE
[Question] Onelogin Logout (SLO) via oidc javascript client

### ISSUE THREAD

**Issue by nixoschu** [onelogin/onelogin-oidc-node#8]
Hi, 
I want to use Onelogin as the IDP for 2 different SPA's (angular apps), so I cloned this repo in order to test different scenarios.

I was able to setup the OIDC Connector in my Onelogin Account and was able to login different Users.

Next I wanted to try to log a User out of "App - A" and recognize it in "App - B". Therefore I started with the Logout itself, leading me to this error: `No end session endpoint url returned` while calling the `signoutRedirect` Method of the `Oidc.UserManager`

I know that you can override specific metadata for the _UserManagerSettings_, so I gave the metadata from onelogin oidc a look. (_<your_endpoint>/oidc/.well-known/openid-configuration_)
There is not a single metadata endpoint which would be close to one that sounds like it would log out a User from all sessions.

**Is this not supported by Onelogin or how can this be achieved ?**

**Comment by richet** [comment]
OneLogins OpenId Connector provider does not currently support single log out. It is road mapped for the future but not currently scheduled. 

As a work around you can logout a user via our standard API. https://developers.onelogin.com/api-docs/1/users/log-user-out

You could also force a login from any app by setting `prompt=login`.

**Comment by belfz** [comment]
Forcing a login with `prompt: "login"` option does not really log the user out - it expects valid credentials for currently logged-in user and does not let switching to another user.

**Comment by mangzee** [comment]
@richet - Do we have an update on this?  This functionality is very much needed :(

**Comment by richet** [comment]
@mangzee We had some other big OIDC related projects this year. SLO is now in our top5 and will be released in 2020.

**Comment by mangzee** [comment]
Thanks @richet  :) As a workaround we are infact using the logout API for now.

**Comment by pitbulk** [comment]
There is a non-official package at https://www.npmjs.com/package/onelogin
which lack the logout method, but I believe it should look like this:
https://gist.github.com/pitbulk/98afb080968cf8e7f8167d01daad9e54

Remember to use API Keys for "authentication only", explanation available here:
https://developers.onelogin.com/api-docs/1/getting-started/working-with-api-credentials

**Comment by PTAdvanced** [comment]
Is there any update on the SLO implementation?

Using this endpoint [https://developers.onelogin.com/api-docs/1/users/log-user-out](https://developers.onelogin.com/api-docs/1/users/log-user-out) is not an option for us, as this endpoint requires the UserID be passed.  However, we do not have access to the userId from the OIDC authenticated user.  We therefore must retrieve the userId using the GetUsers endpoint, searching for the user using the email address.

The problem here is that the GetUsers endpoint requires Read Users, Manage users, Read All, or Manage All scopes.  The Log User Out endpoint only requires Authentication Only scope.

The problem we face is that our OneLogin administrators are unwilling to grant Read Users permission to our API key, as that would give us access to read user information for the entire PLC (we are just one operating company within the PLC).

So there is no solution available to us to log our users out when using OneLogin.

Can you advise when this may be implemented?  Or is there another work around?

**Comment by richet** [comment]
We're currently working on an implementation of the RP Logout flow which is part of the OIDC Session Management spec. https://openid.net/specs/openid-connect-session-1_0.html#RPLogout This will be released in Q1 2021.
